server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone
    username: root
    password: admin
    hikari:
      pool-name: DateHikariCP     # 连接池名
      minimum-idle: 3             # 最小空闲连接数
      idle-timeout: 180000        #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 20       # 最大连接数，默认10
      auto-commit: true           # 从连接池返回的连接的自动提交
      max-lifetime: 1800000       # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      connection-timeout: 300000     # 连接超时时间，默认30000（30秒）
      connection-test-query: SELECT 1   #测试连接是否可用的查询语句
  redis:
    timeout: 10000ms                        # 连接超时时间
    host: 127.0.0.1                   # Redis服务器地址
    port: 6379                              # Redis服务器端口
    database: 0                             # 选择哪个库，默认0库
    password: admin
    lettuce:
      pool:
        max-active: 1024                    # 最大连接数，默认 8
        max-wait: 10000ms                   # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200                       # 最大空闲连接，默认 8
        min-idle: 5                          # 最小空闲连接，默认 0
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml      #配置Mapper映射文件
  type-aliases-package: cn.gao.server.pojo    # 配置MyBatis数据返回类型别名（默认别名是类名）
  configuration:
    map-underscore-to-camel-case: false     #关闭驼峰命名
#mybatis sql 打印（方法接口所在的包，不是mapper.xml文件所在的包）
logging:
  level:
      cn.gao.server.mapper: debug
jwt:
  tokenHeader: Authorization          # JWT存储的请求头
  secret: yeb-secret                  # JWT 加解密使用的密钥
  expiration: 604800                  # JWT 加解密使用的密钥
  tokenHead: Bearer                   # JWT 负载中拿到开头

